name: Print Software Versions

on:
  push:
    branches: [ main ] 

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

      - name: Print Node Version
        run: node --version

      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions] 
    steps:
      - name: Install PostgreSQL and MySQL Clients
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client mysql-client
      
      - name: Install MongoDB Shell (mongosh)
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Print PostgreSQL Version
        run: psql --version

      - name: Print MySQL Version
        run: mysql -V

      - name: Print MongoDB Shell Version
        run: mongosh --version
