name: Print Software Versions
on:
  push:
    branches: main
jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
      - name: Print Node Version
        run: node --version
      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Install libssl1.1 and MongoDB 4.4
        run: |
          # Update package list
          sudo apt-get update
          
          # Install libssl1.1 which is required by MongoDB
          sudo apt-get install -y libssl1.1

          # Add MongoDB 4.4 repository
          sudo apt-get install -y gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          
          # Update package list again to include MongoDB repo
          sudo apt-get update
          
          # Install MongoDB
          sudo apt-get install -y mongodb-org

      - name: Print PostgreSQL Version
        run: psql --version

      - name: Print MySQL Version
        run: mysql -V

      - name: Print MongoDB Version
        run: mongod --version
